{% set name = "langchain-together" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_together-{{ version }}.tar.gz
  sha256: 049aae10eece64b83fa4bd6047571c3524efaa7f53a73968857c89748792ae59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.2.26,<0.3.0
    - langchain-openai >=0.1.16,<0.2.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.1,<4.0.0

test:
  imports:
    - langchain_together
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Together AI and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
